webtalk_init -webtalk_dir E:/INFOTECH/First Semester/Digital system design/Xilinx/ex_1_Dsd_mux/ex_1_Dsd_mux.sim/sim_1/behav/xsim/xsim.dir/comp_mux_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 18 17:43:58 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e43928d2-08a5-451f-b1e1-4af23eb8c81a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e0b45646e32b498f9a1d8fb5cde6db2f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6000_KB" -context "xsim\\usage"
webtalk_transmit -clientid 151909330 -regid "" -xml E:/INFOTECH/First Semester/Digital system design/Xilinx/ex_1_Dsd_mux/ex_1_Dsd_mux.sim/sim_1/behav/xsim/xsim.dir/comp_mux_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/INFOTECH/First Semester/Digital system design/Xilinx/ex_1_Dsd_mux/ex_1_Dsd_mux.sim/sim_1/behav/xsim/xsim.dir/comp_mux_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/INFOTECH/First Semester/Digital system design/Xilinx/ex_1_Dsd_mux/ex_1_Dsd_mux.sim/sim_1/behav/xsim/xsim.dir/comp_mux_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
